### ISSUE TITLE
Hawaii is broken!!

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#364] opened 2019-11-06 23:45 UTC
Is it due to small number of counties? Something is slipping through

**Comment by olyerickson** [comment] 2019-11-11 14:09
Hawaii's "Deep Dive" remains broken... 
![image](https://user-images.githubusercontent.com/358649/68593215-e6943480-0462-11ea-870b-d73d349a766f.png)

**Comment by ChristinavanHal** [comment] 2019-11-26 22:01
My guess is it's because we have some protective elements, but the graphs are scaled in a way that cuts off at zero...

**Comment by kb22** [comment] 2019-12-02 06:21
The issue is same as the other issue (https://github.com/TheRensselaerIDEA/MortalityMinder/issues/534) so closing this one.

**Closed by kb22** 2019-12-02 06:21 UTC
